const dictModel = {
  user: {
    userId: 'userId',
    username: 'username',
    name: 'name',
    email: 'email',
    avatar: 'avatar',
    city: 'city',
    state: 'state', 
    title: 'title',
    employer: 'employer',
    linkGithub: 'linkGithub',
    linkCodepen: 'linkCodepen',
    linkLinkedIn: 'linkLinkedIn',
    linkPortfolioWebsite: 'linkPortfolioWebsite',
    linkResume: 'linkResume',
    bio: 'bio',
    profileStatsVisits: 'profileStatsVisits',
    profileStatsViewsGithub: 'profileStatsViewsGithub',
    profileStatsViewsCodePen: 'profileStatsViewsCodePen',
    profileStatsViewsPortfolio: 'profileStatsViewsPortfolio',
    profileStatsViewsLinkedIn: 'profileStatsViewsLinkedIn',
    profileStatsViewsResume: 'profileStatsViewsResume',
    experience: 'experience',
    timeWithRT: 'timeWithRT',
    rank: 'rank',
    skillsProfessional: 'skillsProfessional',
    skillsSoftware: 'skillsSoftware',
    skillsLanguages: 'skillsLanguages',
    lessonStatus: 'lessonStatus',
    admin: 'admin',
    inactive: 'inactive',
    isProfileSetup: 'isProfileSetup',
    lastLogin: 'lastLogin',
    lastLogout: 'lastLogout',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
  },
  lesson: {
    Id: 'Id',
    title: 'title',
    date: 'date',
    description: 'description',
    lessonTaughtBy: 'lessonTaughtBy',
    lessonAttendees: 'lessonAttendees',
    lessonVotes: 'lessonVotes',
    scheduled: 'scheduled',
    _lessonCreatedBy: '_lessonCreatedBy',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
  },
  intQuestion: {
    Id: 'Id',
    title: 'title',
    description: 'description',
    categories: 'categories',
    answersToQuestion: 'answersToQuestion',
    upVotes: 'upVotes',
    downVotes: 'downVotes',
    _createdByUser: '_createdByUser',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
  },
  intQuestionAnswer: {
    Id: 'Id',
    // title: 'title',
    description: 'description',
    upVotes: 'upVotes',
    downVotes: 'downVotes',
    _createdByUser: '_createdByUser',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
  },
  profileSkill: {
    id: 'id', 
    name: 'name',
    _usersWithSkill: '_usersWithSkill',
    _interviewquestionsWithCategory: '_interviewquestionsWithCategory',
    _createdByUser: '_createdByUser',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
  },
  homeScreenQuote: {
    Id: 'Id',
    quote: 'quote',
    _createdByUser: '_createdByUser',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
  }
}

export default dictModel