version: 0.2

phases:
  build:
    commands:
      - pip install --upgrade awscli
      - npm install
      - npm run webpack
      - aws s3 cp --recursive build/ s3://$WEBSITE_S3_BUCKET --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      - aws cloudformation package --template build/template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

artifacts:
  type: zip
  files:
    - template-export.yml
