// export const SIGN_IN = 'SIGN_IN';
// export const SIGN_UP = 'SIGN_UP'
// export const SIGN_OUT = 'SIGN_OUT'

export const GET_CURRENT_USER_BY_ID = 'GET_CURRENT_USER_BY_ID'

export const FETCH_USERS = 'FETCH_USERS';

export const FETCH_LESSONS = 'FETCH_LESSONS';
export const CREATE_LESSON = 'CREATE_LESSON';

export const GET_LESSON_BY_ID = 'GET_LESSON_BY_ID';
export const EDIT_LESSON_BY_ID = 'EDIT_LESSON_BY_ID';
export const DELETE_LESSON_BY_ID = 'DELETE_LESSON_BY_ID'

export const SELECTED_LESSON = 'SELECTED_LESSON';

export const FETCH_INTERVIEW_QUESTIONS = 'FETCH_INTERVIEW_QUESTIONS';
export const CREATE_INTERVIEW_QUESTION = 'CREATE_INTERVIEW_QUESTION';

export const GET_INTERVIEW_QUESTION_BY_ID = 'GET_INTERVIEW_QUESTION_BY_ID';
export const EDIT_INTERVIEW_QUESTION_BY_ID = 'EDIT_INTERVIEW_QUESTION_BY_ID';
export const DELETE_INTERVIEW_QUESTION_BY_ID = 'DELETE_INTERVIEW_QUESTION_BY_ID';

export const FETCH_INTERVIEW_QUESTIONS_ANSWERS = 'FETCH_INTERVIEW_QUESTIONS_ANSWERS';
export const CREATE_INTERVIEW_QUESTION_ANSWER = 'CREATE_INTERVIEW_QUESTION_ANSWERS';

export const GET_INTERVIEW_QUESTION_ANSWER_BY_ID = 'GET_INTERVIEW_QUESTION_ANSWER_BY_ID';
export const EDIT_INTERVIEW_QUESTION_ANSWER_BY_ID = 'EDIT_INTERVIEW_QUESTION_ANSWER_BY_ID';
export const DELETE_INTERVIEW_QUESTION_ANSWER_BY_ID = 'DELETE_INTERVIEW_QUESTION_ANSWER_BY_ID';

export const FETCH_SKILLS = 'FETCH_SKILLS';
export const CREATE_SKILL = 'CREATE_SKILL';

export const GET_SKILL_BY_ID = 'GET_SKILL_BY_ID';
export const EDIT_SKILL_BY_ID = 'EDIT_SKILL_BY_ID';
export const DELETE_SKILL_BY_ID = 'DELETE_SKILL_BY_ID';

export const FETCH_HOMESCREEN_QUOTES = 'FETCH_HOMESCREEN_QUOTES';


export const FETCHING = 'FETCHING';