// export const SIGN_IN = 'SIGN_IN';
// export const SIGN_UP = 'SIGN_UP'
// export const SIGN_OUT = 'SIGN_OUT'

export const GET_CURRENT_USER_BY_ID = 'GET_CURRENT_USER_BY_ID'

export const FETCH_USERS = 'FETCH_USERS';
export const CREATE_USER = 'CREATE_USER';

export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const EDIT_USER_BY_ID = 'EDIT_USER_BY_ID';
export const DELETE_USER_BY_ID = 'DELETE_USER_BY_ID'

export const ERRORS_FETCH_USERS = 'ERRORS_FETCH_USERS';
export const ERRORS_CREATE_USER = 'ERRORS_CREATE_USER';

export const ERRORS_GET_USER_BY_ID = 'ERRORS_GET_USER_BY_ID';
export const ERRORS_EDIT_USER_BY_ID = 'ERRORS_EDIT_USER_BY_ID';
export const ERRORS_DELETE_USER_BY_ID = 'ERRORS_DELETE_USER_BY_ID'

export const FETCH_LESSONS = 'FETCH_LESSONS';
export const CREATE_LESSON = 'CREATE_LESSON';

export const GET_LESSON_BY_ID = 'GET_LESSON_BY_ID';
export const EDIT_LESSON_BY_ID = 'EDIT_LESSON_BY_ID';
export const DELETE_LESSON_BY_ID = 'DELETE_LESSON_BY_ID'

export const ERRORS_FETCH_LESSONS = 'ERRORS_FETCH_LESSONS';
export const ERRORS_CREATE_LESSON = 'ERRORS_CREATE_LESSON';

export const ERRORS_GET_LESSON_BY_ID = 'ERRORS_GET_LESSON_BY_ID';
export const ERRORS_EDIT_LESSON_BY_ID = 'ERRORS_EDIT_LESSON_BY_ID';
export const ERRORS_DELETE_LESSON_BY_ID = 'ERRORS_DELETE_LESSON_BY_ID'

export const SELECTED_LESSON = 'SELECTED_LESSON';

export const FETCH_INTERVIEW_QUESTIONS = 'FETCH_INTERVIEW_QUESTIONS';
export const CREATE_INTERVIEW_QUESTION = 'CREATE_INTERVIEW_QUESTION';

export const GET_INTERVIEW_QUESTION_BY_ID = 'GET_INTERVIEW_QUESTION_BY_ID';
export const EDIT_INTERVIEW_QUESTION_BY_ID = 'EDIT_INTERVIEW_QUESTION_BY_ID';
export const DELETE_INTERVIEW_QUESTION_BY_ID = 'DELETE_INTERVIEW_QUESTION_BY_ID';

export const ERRORS_FETCH_INTERVIEW_QUESTIONS = 'ERRORS_FETCH_INTERVIEW_QUESTIONS';
export const ERRORS_CREATE_INTERVIEW_QUESTION = 'ERRORS_CREATE_INTERVIEW_QUESTION';

export const ERRORS_GET_INTERVIEW_QUESTION_BY_ID = 'ERRORS_GET_INTERVIEW_QUESTION_BY_ID';
export const ERRORS_EDIT_INTERVIEW_QUESTION_BY_ID = 'ERRORS_EDIT_INTERVIEW_QUESTION_BY_ID';
export const ERRORS_DELETE_INTERVIEW_QUESTION_BY_ID = 'ERRORS_DELETE_INTERVIEW_QUESTION_BY_ID';

export const FETCH_INTERVIEW_QUESTIONS_ANSWERS = 'FETCH_INTERVIEW_QUESTIONS_ANSWERS';
export const CREATE_INTERVIEW_QUESTION_ANSWER = 'CREATE_INTERVIEW_QUESTION_ANSWERS';

export const GET_INTERVIEW_QUESTION_ANSWER_BY_ID = 'GET_INTERVIEW_QUESTION_ANSWER_BY_ID';
export const EDIT_INTERVIEW_QUESTION_ANSWER_BY_ID = 'EDIT_INTERVIEW_QUESTION_ANSWER_BY_ID';
export const DELETE_INTERVIEW_QUESTION_ANSWER_BY_ID = 'DELETE_INTERVIEW_QUESTION_ANSWER_BY_ID';

export const ERRORS_FETCH_INTERVIEW_QUESTIONS_ANSWERS = 'ERRORS_FETCH_INTERVIEW_QUESTIONS_ANSWERS';
export const ERRORS_CREATE_INTERVIEW_QUESTION_ANSWER = 'ERRORS_CREATE_INTERVIEW_QUESTION_ANSWERS';

export const ERRORS_GET_INTERVIEW_QUESTION_ANSWER_BY_ID = 'ERRORS_GET_INTERVIEW_QUESTION_ANSWER_BY_ID';
export const ERRORS_EDIT_INTERVIEW_QUESTION_ANSWER_BY_ID = 'ERRORS_EDIT_INTERVIEW_QUESTION_ANSWER_BY_ID';
export const ERRORS_DELETE_INTERVIEW_QUESTION_ANSWER_BY_ID = 'ERRORS_DELETE_INTERVIEW_QUESTION_ANSWER_BY_ID';

export const FETCH_SKILLS = 'FETCH_SKILLS';
export const CREATE_SKILL = 'CREATE_SKILL';

export const GET_SKILL_BY_ID = 'GET_SKILL_BY_ID';
export const EDIT_SKILL_BY_ID = 'EDIT_SKILL_BY_ID';
export const DELETE_SKILL_BY_ID = 'DELETE_SKILL_BY_ID';

export const ERRORS_FETCH_SKILLS = 'ERRORS_FETCH_SKILLS';
export const ERRORS_CREATE_SKILL = 'ERRORS_CREATE_SKILL';

export const ERRORS_GET_SKILL_BY_ID = 'ERRORS_GET_SKILL_BY_ID';
export const ERRORS_EDIT_SKILL_BY_ID = 'ERRORS_EDIT_SKILL_BY_ID';
export const ERRORS_DELETE_SKILL_BY_ID = 'ERRORS_DELETE_SKILL_BY_ID';

export const FETCH_HOMESCREEN_QUOTES = 'FETCH_HOMESCREEN_QUOTES';

export const ERRORS_FETCH_HOMESCREEN_QUOTES = 'FETCH_HOMESCREEN_QUOTES';

export const FETCHING = 'FETCHING';

