export const CURRENT_USER_GET_BY_ID_REQUEST = 'CURRENT_USER_GET_BY_ID_REQUEST'
export const CURRENT_USER_GET_BY_ID_SUCCESS = 'CURRENT_USER_GET_BY_ID_SUCCESS'
export const CURRENT_USER_GET_BY_ID_ERRORS = 'CURRENT_USER_GET_BY_ID_ERRORS'

// export const GET_CURRENT_USER_BY_ID = 'GET_CURRENT_USER_BY_ID'
// export const ERRORS_GET_CURRENT_USER_BY_ID = 'ERRORS_GET_CURRENT_USER_BY_ID';

export const USERS_GET_ALL_REQUEST = 'USERS_GET_ALL_REQUEST';
export const USERS_GET_ALL_SUCCESS = 'USERS_GET_ALL_SUCCESS';
export const USERS_GET_ALL_ERRORS = 'USERS_GET_ALL_ERRORS';

export const USER_CREATE_BY_ID_REQUEST = 'USER_CREATE_BY_ID_REQUEST';
export const USER_CREATE_BY_ID_SUCCESS = 'USER_CREATE_BY_ID_SUCCESS';
export const USER_CREATE_BY_ID_ERRORS = 'USER_CREATE_BY_ID_ERRORS';

export const USER_GET_BY_ID_REQUEST = 'USER_GET_BY_ID_REQUEST';
export const USER_GET_BY_ID_SUCCESS = 'USER_GET_BY_ID_SUCCESS';
export const USER_GET_BY_ID_ERRORS = 'USER_GET_BY_ID_ERRORS';

export const USER_EDIT_BY_ID_REQUEST = 'USER_EDIT_BY_ID_REQUEST';
export const USER_EDIT_BY_ID_SUCCESS = 'USER_EDIT_BY_ID_SUCCESS';
export const USER_EDIT_BY_ID_ERRORS = 'USER_EDIT_BY_ID_ERRORS';

export const USER_DELETE_BY_ID_REQUEST = 'USER_DELETE_BY_ID_REQUEST'
export const USER_DELETE_BY_ID_SUCCESS = 'USER_DELETE_BY_ID_SUCCESS'
export const USER_DELETE_BY_ID_ERRORS = 'USER_DELETE_BY_ID_ERRORS'

export const LESSONS_GET_ALL_REQUEST = 'LESSONS_GET_ALL_REQUEST';
export const LESSONS_GET_ALL_SUCCESS = 'LESSONS_GET_ALL_SUCCESS';
export const LESSONS_GET_ALL_ERRORS = 'LESSONS_GET_ALL_ERRORS';

export const LESSON_CREATE_BY_ID_REQUEST = 'LESSON_CREATE_BY_ID_REQUEST';
export const LESSON_CREATE_BY_ID_SUCCESS = 'LESSON_CREATE_BY_ID_SUCCESS';
export const LESSON_CREATE_BY_ID_ERRORS = 'LESSON_CREATE_BY_ID_ERRORS';

export const LESSON_GET_BY_ID_REQUEST = 'LESSON_GET_BY_ID_REQUEST';
export const LESSON_GET_BY_ID_SUCCESS = 'LESSON_GET_BY_ID_SUCCESS';
export const LESSON_GET_BY_ID_ERRORS = 'LESSON_GET_BY_ID_ERRORS';

export const LESSON_EDIT_BY_ID_REQUEST = 'LESSON_EDIT_BY_ID_REQUEST';
export const LESSON_EDIT_BY_ID_SUCCESS = 'LESSON_EDIT_BY_ID_SUCCESS';
export const LESSON_EDIT_BY_ID_ERRORS = 'LESSON_EDIT_BY_ID_ERRORS';

export const LESSON_DELETE_BY_ID_REQUEST = 'LESSON_DELETE_BY_ID_REQUEST'
export const LESSON_DELETE_BY_ID_SUCCESS = 'LESSON_DELETE_BY_ID_SUCCESS'
export const LESSON_DELETE_BY_ID_ERRORS = 'LESSON_DELETE_BY_ID_ERRORS'

export const SELECTED_LESSON = 'SELECTED_LESSON';

export const INTERVIEW_QUESTIONS_GET_ALL_REQUEST = 'INTERVIEW_QUESTIONS_GET_ALL_REQUEST';
export const INTERVIEW_QUESTIONS_GET_ALL_SUCCESS = 'INTERVIEW_QUESTIONS_GET_ALL_SUCCESS';
export const INTERVIEW_QUESTIONS_GET_ALL_ERRORS = 'INTERVIEW_QUESTIONS_GET_ALL_ERRORS';

export const INTERVIEW_QUESTION_CREATE_BY_ID_REQUEST = 'INTERVIEW_QUESTION_CREATE_BY_ID_REQUEST';
export const INTERVIEW_QUESTION_CREATE_BY_ID_SUCCESS = 'INTERVIEW_QUESTION_CREATE_BY_ID_SUCCESS';
export const INTERVIEW_QUESTION_CREATE_BY_ID_ERRORS = 'INTERVIEW_QUESTION_CREATE_BY_ID_ERRORS';

export const INTERVIEW_QUESTION_GET_BY_ID_REQUEST = 'INTERVIEW_QUESTION_GET_BY_ID_REQUEST';
export const INTERVIEW_QUESTION_GET_BY_ID_SUCCESS = 'INTERVIEW_QUESTION_GET_BY_ID_SUCCESS';
export const INTERVIEW_QUESTION_GET_BY_ID_ERRORS = 'INTERVIEW_QUESTION_GET_BY_ID_ERRORS';

export const INTERVIEW_QUESTION_EDIT_BY_ID_REQUEST = 'INTERVIEW_QUESTION_EDIT_BY_ID_REQUEST';
export const INTERVIEW_QUESTION_EDIT_BY_ID_SUCCESS = 'INTERVIEW_QUESTION_EDIT_BY_ID_SUCCESS';
export const INTERVIEW_QUESTION_EDIT_BY_ID_ERRORS = 'INTERVIEW_QUESTION_EDIT_BY_ID_ERRORS';

export const INTERVIEW_QUESTION_DELETE_BY_ID_REQUEST = 'INTERVIEW_QUESTION_DELETE_BY_ID_REQUEST'
export const INTERVIEW_QUESTION_DELETE_BY_ID_SUCCESS = 'INTERVIEW_QUESTION_DELETE_BY_ID_SUCCESS'
export const INTERVIEW_QUESTION_DELETE_BY_ID_ERRORS = 'INTERVIEW_QUESTION_DELETE_BY_ID_ERRORS'

export const INTERVIEW_QUESTION_ANSWERS_GET_ALL_REQUEST = 'INTERVIEW_QUESTION_ANSWERS_GET_ALL_REQUEST';
export const INTERVIEW_QUESTION_ANSWERS_GET_ALL_SUCCESS = 'INTERVIEW_QUESTION_ANSWERS_GET_ALL_SUCCESS';
export const INTERVIEW_QUESTION_ANSWERS_GET_ALL_ERRORS = 'INTERVIEW_QUESTION_ANSWERS_GET_ALL_ERRORS';

export const INTERVIEW_QUESTION_ANSWER_CREATE_BY_ID_REQUEST = 'INTERVIEW_QUESTION_ANSWER_CREATE_BY_ID_REQUEST';
export const INTERVIEW_QUESTION_ANSWER_CREATE_BY_ID_SUCCESS = 'INTERVIEW_QUESTION_ANSWER_CREATE_BY_ID_SUCCESS';
export const INTERVIEW_QUESTION_ANSWER_CREATE_BY_ID_ERRORS = 'INTERVIEW_QUESTION_ANSWER_CREATE_BY_ID_ERRORS';

export const INTERVIEW_QUESTION_ANSWER_GET_BY_ID_REQUEST = 'INTERVIEW_QUESTION_ANSWER_GET_BY_ID_REQUEST';
export const INTERVIEW_QUESTION_ANSWER_GET_BY_ID_SUCCESS = 'INTERVIEW_QUESTION_ANSWER_GET_BY_ID_SUCCESS';
export const INTERVIEW_QUESTION_ANSWER_GET_BY_ID_ERRORS = 'INTERVIEW_QUESTION_ANSWER_GET_BY_ID_ERRORS';

export const INTERVIEW_QUESTION_ANSWER_EDIT_BY_ID_REQUEST = 'INTERVIEW_QUESTION_ANSWER_EDIT_BY_ID_REQUEST';
export const INTERVIEW_QUESTION_ANSWER_EDIT_BY_ID_SUCCESS = 'INTERVIEW_QUESTION_ANSWER_EDIT_BY_ID_SUCCESS';
export const INTERVIEW_QUESTION_ANSWER_EDIT_BY_ID_ERRORS = 'INTERVIEW_QUESTION_ANSWER_EDIT_BY_ID_ERRORS';

export const INTERVIEW_QUESTION_ANSWER_DELETE_BY_ID_REQUEST = 'INTERVIEW_QUESTION_ANSWER_DELETE_BY_ID_REQUEST'
export const INTERVIEW_QUESTION_ANSWER_DELETE_BY_ID_SUCCESS = 'INTERVIEW_QUESTION_ANSWER_DELETE_BY_ID_SUCCESS'
export const INTERVIEW_QUESTION_ANSWER_DELETE_BY_ID_ERRORS = 'INTERVIEW_QUESTION_ANSWER_DELETE_BY_ID_ERRORS'

export const CREATE_INTERVIEW_QUESTION_ANSWER = 'CREATE_INTERVIEW_QUESTION_ANSWERS';

export const GET_INTERVIEW_QUESTION_ANSWER_BY_ID = 'GET_INTERVIEW_QUESTION_ANSWER_BY_ID';
export const EDIT_INTERVIEW_QUESTION_ANSWER_BY_ID = 'EDIT_INTERVIEW_QUESTION_ANSWER_BY_ID';
export const DELETE_INTERVIEW_QUESTION_ANSWER_BY_ID = 'DELETE_INTERVIEW_QUESTION_ANSWER_BY_ID';

export const ERRORS_GET_ALL_INTERVIEW_QUESTIONS_ANSWERS = 'ERRORS_GET_ALL_INTERVIEW_QUESTIONS_ANSWERS';
export const ERRORS_CREATE_INTERVIEW_QUESTION_ANSWER = 'ERRORS_CREATE_INTERVIEW_QUESTION_ANSWERS';

export const ERRORS_GET_INTERVIEW_QUESTION_ANSWER_BY_ID = 'ERRORS_GET_INTERVIEW_QUESTION_ANSWER_BY_ID';
export const ERRORS_EDIT_INTERVIEW_QUESTION_ANSWER_BY_ID = 'ERRORS_EDIT_INTERVIEW_QUESTION_ANSWER_BY_ID';
export const ERRORS_DELETE_INTERVIEW_QUESTION_ANSWER_BY_ID = 'ERRORS_DELETE_INTERVIEW_QUESTION_ANSWER_BY_ID';

export const SKILLS_GET_ALL_REQUEST = 'SKILLS_GET_ALL_REQUEST';
export const SKILLS_GET_ALL_SUCCESS = 'SKILLS_GET_ALL_SUCCESS';
export const SKILLS_GET_ALL_ERRORS = 'SKILLS_GET_ALL_ERRORS';

export const SKILL_CREATE_BY_ID_REQUEST = 'SKILL_CREATE_BY_ID_REQUEST';
export const SKILL_CREATE_BY_ID_SUCCESS = 'SKILL_CREATE_BY_ID_SUCCESS';
export const SKILL_CREATE_BY_ID_ERRORS = 'SKILL_CREATE_BY_ID_ERRORS';

export const SKILL_GET_BY_ID_REQUEST = 'SKILL_GET_BY_ID_REQUEST';
export const SKILL_GET_BY_ID_SUCCESS = 'SKILL_GET_BY_ID_SUCCESS';
export const SKILL_GET_BY_ID_ERRORS = 'SKILL_GET_BY_ID_ERRORS';

export const SKILL_EDIT_BY_ID_REQUEST = 'SKILL_EDIT_BY_ID_REQUEST';
export const SKILL_EDIT_BY_ID_SUCCESS = 'SKILL_EDIT_BY_ID_SUCCESS';
export const SKILL_EDIT_BY_ID_ERRORS = 'SKILL_EDIT_BY_ID_ERRORS';

export const SKILL_DELETE_BY_ID_REQUEST = 'SKILL_DELETE_BY_ID_REQUEST';
export const SKILL_DELETE_BY_ID_SUCCESS = 'SKILL_DELETE_BY_ID_SUCCESS';
export const SKILL_DELETE_BY_ID_ERRORS = 'SKILL_DELETE_BY_ID_ERRORS';

export const HOMESCREEN_QUOTES_GET_ALL_REQUEST = 'HOMESCREEN_QUOTES_GET_ALL_REQUEST';
export const HOMESCREEN_QUOTES_GET_ALL_SUCCESS = 'HOMESCREEN_QUOTES_GET_ALL_SUCCESS';
export const HOMESCREEN_QUOTES_GET_ALL_ERRORS = 'HOMESCREEN_QUOTES_GET_ALL_ERRORS';

export const RANKS_GET_ALL_REQUEST = 'RANKS_GET_ALL_REQUEST';
export const RANKS_GET_ALL_SUCCESS = 'RANKS_GET_ALL_SUCCESS';
export const RANKS_GET_ALL_ERRORS = 'RANKS_GET_ALL_ERRORS';

export const FETCHING = 'FETCHING';

// export const GET_ALL_USERS = 'GET_ALL_USERS';
// export const CREATE_USER = 'CREATE_USER';
// export const GET_USER_BY_ID = 'GET_USER_BY_ID';
// export const EDIT_USER_BY_ID = 'EDIT_USER_BY_ID';
// export const DELETE_USER_BY_ID = 'DELETE_USER_BY_ID'
// export const ERRORS_GET_ALL_USERS = 'ERRORS_GET_ALL_USERS';
// export const ERRORS_CREATE_USER = 'ERRORS_CREATE_USER';
// export const ERRORS_GET_USER_BY_ID = 'ERRORS_GET_USER_BY_ID';
// export const ERRORS_EDIT_USER_BY_ID = 'ERRORS_EDIT_USER_BY_ID';
// export const ERRORS_DELETE_USER_BY_ID = 'ERRORS_DELETE_USER_BY_ID'

// export const GET_ALL_LESSONS = 'GET_ALL_LESSONS';
// export const CREATE_LESSON = 'CREATE_LESSON';
// export const GET_LESSON_BY_ID = 'GET_LESSON_BY_ID';
// export const EDIT_LESSON_BY_ID = 'EDIT_LESSON_BY_ID';
// export const DELETE_LESSON_BY_ID = 'DELETE_LESSON_BY_ID'
// export const ERRORS_GET_ALL_LESSONS = 'ERRORS_GET_ALL_LESSONS';
// export const ERRORS_CREATE_LESSON = 'ERRORS_CREATE_LESSON';
// export const ERRORS_GET_LESSON_BY_ID = 'ERRORS_GET_LESSON_BY_ID';
// export const ERRORS_EDIT_LESSON_BY_ID = 'ERRORS_EDIT_LESSON_BY_ID';
// export const ERRORS_DELETE_LESSON_BY_ID = 'ERRORS_DELETE_LESSON_BY_ID'
// export const GET_ALL_INTERVIEW_QUESTIONS_ANSWERS = 'GET_ALL_INTERVIEW_QUESTIONS_ANSWERS';
// export const GET_ALL_INTERVIEW_QUESTIONS = 'GET_ALL_INTERVIEW_QUESTIONS';
// export const CREATE_INTERVIEW_QUESTION = 'CREATE_INTERVIEW_QUESTION';
// export const GET_INTERVIEW_QUESTION_BY_ID = 'GET_INTERVIEW_QUESTION_BY_ID';
// export const EDIT_INTERVIEW_QUESTION_BY_ID = 'EDIT_INTERVIEW_QUESTION_BY_ID';
// export const DELETE_INTERVIEW_QUESTION_BY_ID = 'DELETE_INTERVIEW_QUESTION_BY_ID';
// export const ERRORS_GET_ALL_INTERVIEW_QUESTIONS = 'ERRORS_GET_ALL_INTERVIEW_QUESTIONS';
// export const ERRORS_CREATE_INTERVIEW_QUESTION = 'ERRORS_CREATE_INTERVIEW_QUESTION';
// export const ERRORS_GET_INTERVIEW_QUESTION_BY_ID = 'ERRORS_GET_INTERVIEW_QUESTION_BY_ID';
// export const ERRORS_EDIT_INTERVIEW_QUESTION_BY_ID = 'ERRORS_EDIT_INTERVIEW_QUESTION_BY_ID';
// export const ERRORS_DELETE_INTERVIEW_QUESTION_BY_ID = 'ERRORS_DELETE_INTERVIEW_QUESTION_BY_ID';

// export const GET_ALL_SKILLS = 'GET_ALL_SKILLS';
// export const CREATE_SKILL = 'CREATE_SKILL';
// export const GET_SKILL_BY_ID = 'GET_SKILL_BY_ID';
// export const EDIT_SKILL_BY_ID = 'EDIT_SKILL_BY_ID';
// export const DELETE_SKILL_BY_ID = 'DELETE_SKILL_BY_ID';

// export const ERRORS_GET_ALL_SKILLS = 'ERRORS_GET_ALL_SKILLS';
// export const ERRORS_CREATE_SKILL = 'ERRORS_CREATE_SKILL';
// export const ERRORS_GET_SKILL_BY_ID = 'ERRORS_GET_SKILL_BY_ID';
// export const ERRORS_EDIT_SKILL_BY_ID = 'ERRORS_EDIT_SKILL_BY_ID';
// export const ERRORS_DELETE_SKILL_BY_ID = 'ERRORS_DELETE_SKILL_BY_ID';

// export const GET_ALL_HOMESCREEN_QUOTES = 'GET_ALL_HOMESCREEN_QUOTES';
// export const ERRORS_GET_ALL_HOMESCREEN_QUOTES = 'ERRORS_GET_ALL_HOMESCREEN_QUOTES';